### ISSUE TITLE
I follow this step ,but i got "no rule to make target",can you help me?i try many times,but always the error 

### ISSUE THREAD

**Issue by kitecn** [TrollMafia/Easycwmp-Installation-for-x86#1]
kite@ubuntu:~/lede$ make package/easycwmp/compile  PKG_HASH=skip V=s
make[2]: Entering directory '/home/kite/lede/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/kite/lede/scripts/config'
time: target/linux/prereq#0.23#0.19#0.42
make[1]: Entering directory '/home/kite/lede'
make[1]: *** No rule to make target 'package/easycwmp/compile'.  Stop.
make[1]: Leaving directory '/home/kite/lede'
make: *** [/home/kite/lede/include/toplevel.mk:231: package/easycwmp/compile] Error 2
kite@ubuntu:~/lede$ make package/easycwmp/compile  PKG_HASH=skip V=sc

**Comment by TrollMafia** [comment]
Firstly use : `make menuconfig` then select the package.

**Comment by kitecn** [comment]
hi:
    I try to download the full source and lnks file, modify  cwmp.h as patch tips
the error is still when compling。 
“make[3]: *** No targets specified and no makefile found.  Stop.”
***@***.***:~/lede$ find . -name cwmp.h
./build_dir/target-x86_64_musl/easycwmp/easycwmp-1.8.5/src/cwmp.h
***@***.***:~/lede$ vim ./build_dir/target-x86_64_musl/easycwmp/easycwmp-1.8.5/src/cwmp.h
***@***.***:~/lede$



Patch is simple:

--- a/src/cwmp.h
+++ b/src/cwmp.h
@@ -142,7 +142,7 @@ struct cwmp_internal {
};

extern struct cwmp_internal *cwmp;
-struct event_code event_code_array[__EVENT_MAX];
+extern struct event_code event_code_array[__EVENT_MAX];

static void cwmp_periodic_inform(struct uloop_timeout *timeout);
static void cwmp_do_inform(struct uloop_timeout *timeout); 

./scripts/feeds update -a && ./scripts/feeds install -a
tar -xzvf 
make package/easycwmp/compile  PKG_HASH=skip V=s
wget https://easycwmp.org/download/easycwmp-1.8.6.tar.gz





make package/easycwmp/compile  PKG_HASH=skip V=s
64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" ;
make[3]: Entering directory '/home/kite/lede/build_dir/target-x86_64_musl/easycwmp/easycwmp-1.8.5'
make[3]: *** No targets specified and no makefile found.  Stop.
make[3]: Leaving directory '/home/kite/lede/build_dir/target-x86_64_musl/easycwmp/easycwmp-1.8.5'
make[2]: *** [Makefile:110: /home/kite/lede/build_dir/target-x86_64_musl/easycwmp/easycwmp-1.8.5/.built] Error 2
make[2]: Leaving directory '/home/kite/lede/package/easycwmp'
time: package/easycwmp/compile#0.43#0.31#0.67
    ERROR: package/easycwmp failed to build.
make[1]: *** [package/Makefile:116: package/easycwmp/compile] Error 1
make[1]: Leaving directory '/home/kite/lede'
make: *** [/home/kite/lede/include/toplevel.mk:231: package/easycwmp/compile] Error 2

Create a directory in package/easycwmp/patches, here create a txt file with below patch and then compile

--- easycwmp-1.8.6/configure.ac 2019-12-17 12:03:19.000000000 +0100
+++ easycwmp-1.8.6.modified/configure.ac 2022-09-07 10:13:18.364877798 +0200
@@ -1,5 +1,4 @@
AC_INIT([easycwmpd], [1.8.6], ***@***.***)
-AM_INIT_AUTOMAKE
AC_CONFIG_SRCDIR([src/easycwmp.c])




kitecn
 
From: TrollMafia
Date: 2024-06-21 11:21
To: TrollMafia/Easycwmp-Installation-for-x86
CC: kitecn; Author
Subject: Re: [TrollMafia/Easycwmp-Installation-for-x86] I follow this step ,but i got "no rule to make target",can you help me?i try many times,but always the error (Issue #1)
Can you share more details?

**Comment by TrollMafia** [comment]
Did you first build the toolchain?

**Comment by kitecn** [comment]
I have tried to follow your steps and the steps given by the official website, and the official patch, but the error still exists. I used the lean "https://github.com/coolsnowwolf/lede" source code and tried the openwrt official website source code, but the error still exists.


kitecn
 
From: TrollMafia
Date: 2024-06-25 12:03
To: TrollMafia/Easycwmp-Installation-for-x86
CC: kitecn; Author
Subject: Re: [TrollMafia/Easycwmp-Installation-for-x86] I follow this step ,but i got "no rule to make target",can you help me?i try many times,but always the error (Issue #1)
Did you first build the toolchain?
―

**Comment by TrollMafia** [comment]
Can you provide the screenshot of the error and also share the detailed steps you took.

**Comment by kitecn** [comment]
I have successfully compiled OPenwrt, EasyCwmp as a Package, re-compiled after Make menuconfig chekced, whether it is compiled alone or as a whole, toolchain is compiled, I try to make clean and recompile , it doesn't work, thank you very much for your reply。Attached is my compile log



kitecn
 
From: TrollMafia
Date: 2024-06-26 03:01
To: TrollMafia/Easycwmp-Installation-for-x86
CC: kitecn; Author
Subject: Re: [TrollMafia/Easycwmp-Installation-for-x86] I follow this step ,but i got "no rule to make target",can you help me?i try many times,but always the error (Issue #1)
Can you provide the screenshot of the error and also share the detailed steps you took.
―

**Comment by TrollMafia** [comment]
I cant see your log. Can you check it again?

**Comment by kitecn** [comment]
[MobaXterm_192.168.100.111_20240627_145339.txt](https://github.com/user-attachments/files/16091891/MobaXterm_192.168.100.111_20240627_145339.txt)
thanks very much

**Comment by TrollMafia** [comment]
Assuming you had build the toolchain and libmicroxml package first then the easycwmp, in the the makefile of easycwmp : line 116. There is the issue I can see in the log. Can you check what code is written on line 116.

**Comment by TrollMafia** [comment]
If your error is solved, then I am closing this issue.

**Comment by kitecn** [comment]
There are still errors, I looked up the source code of 116 lines, I have no ability to modify it, i'm given up, thank you for your kind help. Close the issuse.



kitecn
 
From: TrollMafia
Date: 2024-07-19 18:29
To: TrollMafia/Easycwmp-Installation-for-x86
CC: kitecn; Author
Subject: Re: [TrollMafia/Easycwmp-Installation-for-x86] I follow this step ,but i got "no rule to make target",can you help me?i try many times,but always the error (Issue #1)
If your error is solved, then I am closing this issue.
―
